In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
url='heart (1).csv'
df=pd.read_csv(url)

In [15]:
print(df.shape)
print(df.info())

(303, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   gender    303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB
None


In [17]:
print(df.head())

   age  gender  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0   63       1   3       145   233    1        0      150      0      2.3   
1   37       1   2       130   250    0        1      187      0      3.5   
2   41       0   1       130   204    0        0      172      0      1.4   
3   56       1   1       120   236    0        1      178      0      0.8   
4   57       0   0       120   354    0        1      163      1      0.6   

   slope  ca  thal  target  
0      0   0     1       1  
1      0   0     2       1  
2      2   0     2       1  
3      2   0     2       1  
4      2   0     2       1  


In [19]:
df.dtypes

age           int64
gender        int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [21]:
# to know unique values
df.nunique()

age          41
gender        2
cp            4
trestbps     49
chol        152
fbs           2
restecg       3
thalach      91
exang         2
oldpeak      40
slope         3
ca            5
thal          4
target        2
dtype: int64

In [25]:
# change the numeric type to categorical variables
df['gender'] = df['gender'].astype('float')
df['cp'] = df['cp'].astype('object')
df['fbs'] = df['fbs'].astype('object')
df['restecg'] = df['restecg'].astype('object')
df['exang'] = df['exang'].astype('object')
df['slope'] = df['slope'].astype('object')
df['ca'] = df['ca'].astype('object')
df['thal'] = df['thal'].astype('object')
df.dtypes

age           int64
gender      float64
cp           object
trestbps      int64
chol          int64
fbs          object
restecg      object
thalach       int64
exang        object
oldpeak     float64
slope        object
ca           object
thal         object
target        int64
dtype: object

In [27]:
print(df.head())

   age  gender cp  trestbps  chol fbs restecg  thalach exang  oldpeak slope  \
0   63     1.0  3       145   233   1       0      150     0      2.3     0   
1   37     1.0  2       130   250   0       1      187     0      3.5     0   
2   41     0.0  1       130   204   0       0      172     0      1.4     2   
3   56     1.0  1       120   236   0       1      178     0      0.8     2   
4   57     0.0  0       120   354   0       1      163     1      0.6     2   

  ca thal  target  
0  0    1       1  
1  0    2       1  
2  0    2       1  
3  0    2       1  
4  0    2       1  


In [29]:
df.isnull().sum()

age         0
gender      0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [31]:
df['ca'].unique()

array([0, 2, 1, 3, 4], dtype=object)

In [33]:
# to count the number in of each category decending order
print(df.ca.value_counts())

df[df['ca']==4]

ca
0    175
1     65
2     38
3     20
4      5
Name: count, dtype: int64


age  gender cp  trestbps  chol fbs restecg  thalach exang  oldpeak slope  \
92    52     1.0  2       138   223   0       1      169     0      0.0     2   
158   58     1.0  1       125   220   0       1      144     0      0.4     1   
163   38     1.0  2       138   175   0       1      173     0      0.0     2   
164   38     1.0  2       138   175   0       1      173     0      0.0     2   
251   43     1.0  0       132   247   1       0      143     1      0.1     1   

    ca thal  target  
92   4    2       1  
158  4    3       1  
163  4    2       1  
164  4    2       1  
251  4    3       0

In [35]:
df.loc[df['ca']==4,'ca']=np.NaN

In [37]:
df['ca'].unique()

array([0, 2, 1, 3, nan], dtype=object)

In [39]:
df['thal'].unique()

array([1, 2, 3, 0], dtype=object)

In [41]:
df.thal.value_counts()

thal
2    166
3    117
1     18
0      2
Name: count, dtype: int64

In [43]:
df.loc[df['thal']==0,'thal']=np.NaN

In [45]:
df['thal'].unique()

array([1, 2, 3, nan], dtype=object)

In [47]:
df.isna().sum()

age         0
gender      0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          5
thal        2
target      0
dtype: int64

In [49]:
df.iloc[0]

age          63
gender      1.0
cp            3
trestbps    145
chol        233
fbs           1
restecg       0
thalach     150
exang         0
oldpeak     2.3
slope         0
ca            0
thal          1
target        1
Name: 0, dtype: object

In [51]:
print(df.mode())
print(df.mode().iloc[0])

    age  gender   cp  trestbps  chol  fbs restecg  thalach exang  oldpeak  \
0  58.0     1.0    0     120.0   197    0       1    162.0     0      0.0   
1   NaN     NaN  NaN       NaN   204  NaN     NaN      NaN   NaN      NaN   
2   NaN     NaN  NaN       NaN   234  NaN     NaN      NaN   NaN      NaN   

  slope   ca thal  target  
0     2    0    2     1.0  
1   NaN  NaN  NaN     NaN  
2   NaN  NaN  NaN     NaN  
age          58.0
gender        1.0
cp              0
trestbps    120.0
chol          197
fbs             0
restecg         1
thalach     162.0
exang           0
oldpeak       0.0
slope           2
ca              0
thal            2
target        1.0
Name: 0, dtype: object


In [53]:
print(df.mean())
print(df.mean().iloc[0:14])

age          54.366337
gender        0.683168
cp            0.966997
trestbps    131.623762
chol        246.264026
fbs           0.148515
restecg       0.528053
thalach     149.646865
exang         0.326733
oldpeak       1.039604
slope          1.39934
ca            0.674497
thal          2.328904
target        0.544554
dtype: object
age          54.366337
gender        0.683168
cp            0.966997
trestbps    131.623762
chol        246.264026
fbs           0.148515
restecg       0.528053
thalach     149.646865
exang         0.326733
oldpeak       1.039604
slope          1.39934
ca            0.674497
thal          2.328904
target        0.544554
dtype: object


In [57]:
#df = df.fillna(df.median())
df = df.fillna(df.mode().iloc[0])
df.isnull().sum()

age         0
gender      0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [59]:
duplicates = df[df.duplicated()]
print(duplicates)

     age  gender  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
164   38     1.0   2       138   175    0        1      173      0      0.0   

     slope  ca  thal  target  
164      2   0     2       1  


In [61]:
df_cleaned = df.drop_duplicates()
print(df_cleaned)

     age  gender  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63     1.0   3       145   233    1        0      150      0      2.3   
1     37     1.0   2       130   250    0        1      187      0      3.5   
2     41     0.0   1       130   204    0        0      172      0      1.4   
3     56     1.0   1       120   236    0        1      178      0      0.8   
4     57     0.0   0       120   354    0        1      163      1      0.6   
..   ...     ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57     0.0   0       140   241    0        1      123      1      0.2   
299   45     1.0   3       110   264    0        1      132      0      1.2   
300   68     1.0   0       144   193    1        1      141      0      3.4   
301   57     1.0   0       130   131    0        1      115      1      1.2   
302   57     0.0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1

In [63]:
#df['A'].fillna('Unknown', inplace=True)  #replace with specific value
#df['A'].fillna(df['A'].mean(), inplace=True)  #replace with mean
#df.drop('gender', axis=1, inplace=True)      #to drop coloumn